dist: trusty

sudo: required

addons:
  chrome: stable

language: node_js

before_install:
  - npm install -g greenkeeper-lockfile
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

install:
  - npm install

before_script:
  - greenkeeper-lockfile-update
  - ./cc-test-reporter before-build

script:
  - ng lint
  - ng test:cov
  - ng test:e2e
  - ng build

after_script:
  - greenkeeper-lockfile-upload
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
